### ISSUE TITLE
Cannot open database connection with default name.

### ISSUE THREAD

**Issue by Wisser** [aferrandi/dbtarzan#109]
**Describe the bug**
When you initially define a database connection, it is called "<NEW>" unless you manually change the name. However, when you double-click on this connection, nothing happens, i.e. you cannot work with this connection.

Only after changing the name and removing the angle brackets, it works. This is very irritating for people who see the tool for the first time (like me), and leave the default name for now.

**To Reproduce**
1. Go to 'Edit -> Edit Connections', keep default name
2. Double click on connection
3. Nothing happens

**Expected behavior**
More than nothing ;)

**Desktop (please complete the following information):**
 - Windows 11
 - 1.25

**Comment by aferrandi** [comment]
I will fix it soon.

By now if you have that problem you can probably see the path of the configuration file in the log.

![image](https://user-images.githubusercontent.com/1436546/141777444-8107fb43-b6aa-4b62-82e3-4107fe6f4e80.png)

If I remember correctly you can just remove the file with that path(which will remove all database connections), start dbtarzan again and enter the database connection with a new name.
Or, if you have several database connections, you can edit the file in an editor and change the connection name.

**Comment by Wisser** [comment]
Thanks for pointing out this file, but to work around the issue, it's not necessary to edit it manually. It is enough to change the name of the connection in the user interface itself.

**Comment by aferrandi** [comment]
Now it is only possible for a connection to have a name composed by letters, numbers and characters '_' and '-'
