### ISSUE TITLE
Establishing connection with SQL Server

### ISSUE THREAD

**Issue by iksub** [aferrandi/dbtarzan#76]
Hello, What does this connection error mean:
Querying the database LeaseNet got:Building the dbWorker with the driver com.microsoft.sqlserver.jdbc.SQLServerDriver got the exception of type java.lang.UnsupportedClassVersionError: at:
dbtarzan.db.ConnectionBuilder.buildDBWorker(ConnectionBuilder.scala:17)
dbtarzan.db.ConnectionBuilder$.buildDBWorker(ConnectionBuilder.scala:50)
dbtarzan.config.actor.ConnectionsWorker.getDBWorker(ConnectionsWorker.scala:21)
dbtarzan.config.actor.ConnectionsWorker.dbtarzan$config$actor$ConnectionsWorker$$queryDatabase(ConnectionsWorker.scala:38)
dbtarzan.config.actor.ConnectionsWorker$$anonfun$receive$1.applyOrElse(ConnectionsWorker.scala:65)
akka.actor.Actor.aroundReceive(Actor.scala:517)
akka.actor.Actor.aroundReceive$(Actor.scala:515)
dbtarzan.config.actor.ConnectionsWorker.aroundReceive(ConnectionsWorker.scala:13)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
akka.actor.ActorCell.invoke(ActorCell.scala:559)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by aferrandi** [comment]
java.lang.UnsupportedClassVersionError:should mean that the java version of the application is not the same as the one of the JDBC driver.
DBTarzan works with Java 8 , probably the JDBC driver jar is for a different version.

**Comment by aferrandi** [comment]
No more news about this, probably fixed.
